### ISSUE TITLE
Portuguese keyboard layout

### ISSUE THREAD

**Issue by hugok79** [pardus/pardus-lightdm-greeter#5]
Portuguese keyboard layout does not appear, only **Turkish**, **Turkish F** and **English** is displayed.
Also, the keyboard layouts appear in Turkish language.

In Keyboard module:

("keyboard-layouts", "tr::Türkçe tr:f:Türkçe_F us::İngilizce", "keyboard")

**Comment by sulincix** [comment]
you can define your keyboard layout list from /etc/pardus/greeter.conf.d/portuguese.conf

Pardus is turkish distribution so default variables predefined for turkish :D

**Comment by sulincix** [comment]
Fixed: https://github.com/pardus/pardus-lightdm-greeter/commit/31388c3dfdbe58ff8582d235ab4ac8bca76827e2

Behaviour: 

1. If you change config, uses config.

2. If your default keyboard layout is not Turkish, keyboard layout menu show "default" and doesn't change your keyboard layout.

3. If your keyboard is Turkish and config is default, uses config.
